name = "Ringo"
version = "0.0.2 alpha"
license = "MIT"
author = "St Maxwell"
maintainer = "st_maxwell@outlook.com"
copyright = "Copyright 2023, St Maxwell"

[build]
auto-executables = true
link = ["cint","openblas"]

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive.git"

[[test]]
name = "cint"
source-dir = "test/cint"
main = "tester.f90"

[[test]]
name = "mole"
source-dir = "test/mole"
main = "test.f90"

[preprocess.cpp]
suffixes = ["F90"]
macros = ["DEBUG","PROJECT_ROOT=C:/Users/St_Maxwell/Documents/Ringo"]
